site_name: Generative Models
site_url: https://sut-cs-gm.github.io
theme:
  name: material
  custom_dir: overrides
  font:
    text: Ubuntu
    code: Red Hat Mono
#  logo: assets/logo.png
  favicon: assets/favicon/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: black
      accent: red

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: black
      accent: red
  features:
    - navigation.tabs
    - toc.integrate
    # - navigation.indexes

plugins:
  - search
  - blog:
      blog_toc: true
      post_readtime_words_per_minute: 250
      pagination_per_page: 5
      archive: true
      archive_name: Archive
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy/MM
      archive_pagination_per_page: 10
      archive_toc: false
      categories_pagination_per_page: 10
      categories_toc: false
  - tags:
      tags_file: blog/tags.md
  # - social
  # - offline

extra:
  generator: false
  social:
    - icon: material/email-outline
      link: mailto:sut-cs-gm@gmail.com
    - icon: fontawesome/brands/github
      link: https://github.com/sut-cs-gm
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@sut-cs-gm
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/sut-cs-gm
    - icon: fontawesome/brands/telegram
      link: https://t.me/sut-cs-gm

#copyright: Made by @iMohammad97

nav:
  - Home:
    - index.md
  - Course Material:
    - slides/index.md
  - Homeworks:
    - homeworks/index.md
  - Exams:
    - exams/midterm.md
    - exams/final.md
  - Resources:
    - resources/index.md

extra_css:
  - stylesheets/extra.css
  - stylesheets/vazirmatn.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - admonition
  - pymdownx.blocks.caption
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - abbr

  
